// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnO1Ka7kq-R5qxCC_97BwfooxQYATOF08',
    appId: '1:34430649210:web:9ba75dd11c711409de4cc3',
    messagingSenderId: '34430649210',
    projectId: 'testproject-25789',
    authDomain: 'testproject-25789.firebaseapp.com',
    databaseURL: 'https://testproject-25789-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-25789.appspot.com',
    measurementId: 'G-3JPK1CWG30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-59OwtXLHT8g2_l7je0-YN-NdmaLKeuQ',
    appId: '1:34430649210:android:f2115a563ac0fd03de4cc3',
    messagingSenderId: '34430649210',
    projectId: 'testproject-25789',
    databaseURL: 'https://testproject-25789-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-25789.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSsFWxvQaEqVRCM7D9MhXVg2Nsc68APRo',
    appId: '1:34430649210:ios:051fd64687e4ee68de4cc3',
    messagingSenderId: '34430649210',
    projectId: 'testproject-25789',
    databaseURL: 'https://testproject-25789-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-25789.appspot.com',
    iosBundleId: 'com.example.flutterBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSsFWxvQaEqVRCM7D9MhXVg2Nsc68APRo',
    appId: '1:34430649210:ios:0a85636a516457d6de4cc3',
    messagingSenderId: '34430649210',
    projectId: 'testproject-25789',
    databaseURL: 'https://testproject-25789-default-rtdb.firebaseio.com',
    storageBucket: 'testproject-25789.appspot.com',
    iosBundleId: 'com.example.flutterBase.RunnerTests',
  );
}
